(()=>{
const K='bplus_features_v1';
const base=()=>{try{return JSON.parse(localStorage.getItem(K))||{employees:[],stores:[],courses:[],absences:[],notifications:[],history:[]}}catch(e){return{employees:[],stores:[],courses:[],absences:[],notifications:[],history:[]}}};
let S=base(); const save=()=>localStorage.setItem(K,JSON.stringify(S));
const esc=x=>String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const page=(id,title,sub,body)=>{if(document.getElementById(id))return;let m=document.querySelector('.content');m.insertAdjacentHTML('beforeend',`<section class="page" id="${id}"><h1 class="title">${title}</h1><p class="subtitle">${sub}</p>${body}</section>`)};
page('fx-dip','Dipendenti','Anagrafica e gestione del personale.','<div class="actions"><button class="btn" id="fxNewEmp">+ Nuovo dipendente</button></div><div class="tablewrap"><table class="table"><thead><tr><th>Nome</th><th>Email</th><th>Negozio</th><th>Ruolo</th><th>Contratto</th><th>Ore</th><th>Azioni</th></tr></thead><tbody id="fxEmpRows"></tbody></table></div>');
page('fx-corsi','Corsi','Formazione e sessioni.','<div class="actions"><button class="btn" id="fxNewCourse">+ Nuovo corso</button></div><div class="tablewrap"><table class="table"><thead><tr><th>Titolo</th><th>Ente</th><th>Data</th><th>Stato</th><th>Obbl.</th><th>Azioni</th></tr></thead><tbody id="fxCourseRows"></tbody></table></div>');
page('fx-negozi','Punti vendita','Orari e personale minimo.','<div class="actions"><button class="btn" id="fxNewStore">+ Nuovo negozio</button></div><div class="tablewrap"><table class="table"><thead><tr><th>Codice</th><th>Nome</th><th>Indirizzo</th><th>Min/giorno</th><th>Azioni</th></tr></thead><tbody id="fxStoreRows"></tbody></table></div>');
page('fx-report','Report','Riepiloghi ed esportazione.','<div class="grid3"><div class="card"><h2>Turni</h2><button class="btn" id="fxShiftsCsv">CSV</button></div><div class="card"><h2>Assenze</h2><button class="btn" id="fxAbsCsv">CSV</button></div><div class="card"><h2>Personale</h2><button class="btn" id="fxEmpCsv">CSV</button></div></div><div class="section"><div class="card"><h2>Riepilogo</h2><div id="fxSummary" class="reportbox"></div></div></div>');
page('fx-notifiche','Notifiche','Avvisi del gestionale.','<div class="actions"><button class="btn secondary" id="fxRead">Segna tutte lette</button><button class="btn danger" id="fxClear">Cancella</button></div><div id="fxNotifRows"></div>');
const addNav=(container,id,label)=>{let host=document.querySelector(container);if(host&&!host.querySelector('[data-page="'+id+'"]'))host.insertAdjacentHTML('beforeend',`<button class="nav" data-page="${id}">${label}</button>`)};
addNav('.side','fx-dip','👥 Dipendenti');addNav('.side','fx-corsi','🎓 Corsi');addNav('.side','fx-negozi','🏪 Punti vendita');addNav('.side','fx-report','📊 Report');addNav('.side','fx-notifiche','🔔 Notifiche');
addNav('.drawer','fx-dip','👥 Dipendenti');addNav('.drawer','fx-corsi','🎓 Corsi');addNav('.drawer','fx-negozi','🏪 Punti vendita');addNav('.drawer','fx-report','📊 Report');addNav('.drawer','fx-notifiche','🔔 Notifiche');
function nav(){document.querySelectorAll('[data-page]').forEach(b=>{b.onclick=e=>{e.preventDefault();document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));let p=document.getElementById(b.dataset.page);if(p)p.classList.add('active');document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===b.dataset.page));let d=document.getElementById('drawer');let o=document.getElementById('backdrop');if(d)d.classList.remove('open');if(o)o.classList.remove('open');render()}})}
function seed(){if(S.employees.length)return;S.employees=[{id:1,nome:'Marco',cognome:'Rossi',email:'',negozio:'GAG',ruolo:3,contratto:'indeterminato',ore:40},{id:2,nome:'Marco',cognome:'Ferrari',email:'',negozio:'GAG',ruolo:2,contratto:'indeterminato',ore:40},{id:3,nome:'Laura',cognome:'Bianchi',email:'',negozio:'VAR',ruolo:1,contratto:'indeterminato',ore:40}];S.stores=[{id:'GAG',nome:'Brico+ Gaggiolo',addr:'Gaggiolo',min:2},{id:'COC',nome:'Brico+ Cocquio',addr:'Cocquio',min:1},{id:'DAV',nome:'Brico+ Daverio',addr:'Daverio',min:1},{id:'VAR',nome:'Brico+ Varese',addr:'Varese',min:1}];save()}
function modal(title,html,done){let b=document.createElement('div');b.className='modalback open';b.innerHTML='<div class="modal"><h2>'+title+'</h2>'+html+'<div class="modalfoot"><button class="btn secondary" id="fxCancel">Annulla</button><button class="btn" id="fxSave">Salva</button></div></div>';document.body.appendChild(b);b.querySelector('#fxCancel').onclick=()=>b.remove();b.querySelector('#fxSave').onclick=()=>{if(done(b))b.remove()}}
function input(id,l,v=''){return `<div class="field"><label>${l}</label><input id="${id}" value="${esc(v)}"></div>`}
function render(){document.getElementById('fxEmpRows').innerHTML=S.employees.map(e=>`<tr><td>${esc(e.nome+' '+e.cognome)}</td><td>${esc(e.email)}</td><td>${esc(e.negozio)}</td><td>${e.ruolo==3?'Titolare':e.ruolo==2?'Direttore':'Lavoratore'}</td><td>${esc(e.contratto)}</td><td>${esc(e.ore)}</td><td><button class="btn secondary" onclick="FX.emp(${e.id})">Modifica</button> <button class="btn danger" onclick="FX.delEmp(${e.id})">×</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Nessun dipendente.</td></tr>';
document.getElementById('fxCourseRows').innerHTML=S.courses.map(c=>`<tr><td>${esc(c.title)}</td><td>${esc(c.ente)}</td><td>${esc(c.date)}</td><td>${esc(c.status)}</td><td>${c.required?'Sì':'No'}</td><td><button class="btn secondary" onclick="FX.course(${c.id})">Modifica</button> <button class="btn danger" onclick="FX.delCourse(${c.id})">×</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Nessun corso.</td></tr>';
document.getElementById('fxStoreRows').innerHTML=S.stores.map(s=>`<tr><td>${esc(s.id)}</td><td>${esc(s.nome)}</td><td>${esc(s.addr)}</td><td>${esc(s.min)}</td><td><button class="btn secondary" onclick="FX.store('${s.id}')">Modifica</button> <button class="btn danger" onclick="FX.delStore('${s.id}')">×</button></td></tr>`).join('');
document.getElementById('fxSummary').textContent='Dipendenti: '+S.employees.length+'\nNegozi: '+S.stores.length+'\nCorsi: '+S.courses.length+'\nAssenze: '+S.absences.length+'\nNotifiche: '+S.notifications.length;
document.getElementById('fxNotifRows').innerHTML=S.notifications.slice().reverse().map(n=>`<div class="notice"><b>${esc(n.title)}</b><br>${esc(n.body)}<br><small>${esc(n.when)}</small></div>`).join('')||'<div class="empty">Nessuna notifica.</div>';}
function emp(id){let e=S.employees.find(x=>x.id===id)||{id:Date.now(),nome:'',cognome:'',email:'',negozio:'GAG',ruolo:1,contratto:'indeterminato',ore:40};modal(id?'Modifica dipendente':'Nuovo dipendente',input('n','Nome',e.nome)+input('c','Cognome',e.cognome)+input('em','Email',e.email)+input('st','Negozio',e.negozio)+input('r','Ruolo',e.ruolo)+input('o','Ore',e.ore),b=>{e.nome=b.querySelector('#n').value;e.cognome=b.querySelector('#c').value;e.email=b.querySelector('#em').value;e.negozio=b.querySelector('#st').value;e.ruolo=Number(b.querySelector('#r').value)||1;e.ore=Number(b.querySelector('#o').value)||40;if(!e.nome||!e.cognome)return false;if(!id)S.employees.push(e);save();render()})}
function course(id){let c=S.courses.find(x=>x.id===id)||{id:Date.now(),title:'',ente:'',date:'',status:'programmato',required:false};modal(id?'Modifica corso':'Nuovo corso',input('t','Titolo',c.title)+input('e','Ente',c.ente)+input('d','Data',c.date),b=>{c.title=b.querySelector('#t').value;c.ente=b.querySelector('#e').value;c.date=b.querySelector('#d').value;if(!id)S.courses.push(c);save();render()})}
function store(id){let s=S.stores.find(x=>x.id===id)||{id:'NEW',nome:'',addr:'',min:1};modal(id?'Modifica negozio':'Nuovo negozio',input('i','Codice',s.id)+input('n','Nome',s.nome)+input('a','Indirizzo',s.addr)+input('m','Minimo/giorno',s.min),b=>{s.id=b.querySelector('#i').value.toUpperCase();s.nome=b.querySelector('#n').value;s.addr=b.querySelector('#a').value;s.min=Number(b.querySelector('#m').value)||1;if(!id)S.stores.push(s);save();render()})}
function csv(rows){return rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n')} function dl(n,t){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/csv'}));a.download=n;a.click()}
window.FX={emp,course,store,delEmp:id=>{S.employees=S.employees.filter(e=>e.id!==id);save();render()},delCourse:id=>{S.courses=S.courses.filter(c=>c.id!==id);save();render()},delStore:id=>{S.stores=S.stores.filter(s=>s.id!==id);save();render()}};
seed();nav();render();document.getElementById('fxNewEmp').onclick=()=>emp();document.getElementById('fxNewCourse').onclick=()=>course();document.getElementById('fxNewStore').onclick=()=>store();document.getElementById('fxRead').onclick=()=>{S.notifications.forEach(n=>n.read=true);save();render()};document.getElementById('fxClear').onclick=()=>{S.notifications=[];save();render()};document.getElementById('fxEmpCsv').onclick=()=>dl('dipendenti.csv',csv([['Nome','Email','Negozio','Ruolo','Ore'],...S.employees.map(e=>[e.nome+' '+e.cognome,e.email,e.negozio,e.ruolo,e.ore])]));document.getElementById('fxAbsCsv').onclick=()=>dl('assenze.csv',csv([['Dipendente','Tipo','Dal','Al'],...S.absences.map(a=>[a.employeeId,a.type,a.from,a.to])]));document.getElementById('fxShiftsCsv').onclick=()=>dl('turni.csv',csv([['Data','Dipendente','Negozio','In','Out'],...(JSON.parse(localStorage.getItem('bplus_data_v2')||'{"shifts":[]}').shifts||[]).map(s=>[s.date,s.employeeId,s.store,s.in,s.out])]));
})();