/* B+ SW v10 - deep mobile navigation fix */
const MOBILE_CSS=`
html,body{width:100%;min-height:100%;overflow-x:hidden;-webkit-text-size-adjust:100%;touch-action:manipulation}
body{padding-bottom:calc(76px + env(safe-area-inset-bottom))}
#app-main{min-height:100dvh;width:100%;display:flex!important;visibility:visible!important}.main{min-width:0;width:100%}.content{padding-bottom:calc(100px + env(safe-area-inset-bottom));overflow-x:hidden}
#bottombar{position:fixed!important;left:0!important;right:0!important;bottom:0!important;width:100%!important;height:calc(68px + env(safe-area-inset-bottom))!important;padding:6px 6px env(safe-area-inset-bottom)!important;display:flex!important;z-index:2147483000!important;pointer-events:none!important;touch-action:manipulation!important;background:var(--bg2,#1e1e1e)!important;border-top:1px solid var(--border,#333)!important;box-shadow:0 -6px 20px rgba(0,0,0,.35)!important}
#bottombar .bb-item{flex:1!important;min-width:0!important;height:54px!important;display:flex!important;align-items:center!important;justify-content:center!important;flex-direction:column!important;gap:2px!important;padding:5px 2px!important;border-radius:10px!important;cursor:pointer!important;-webkit-tap-highlight-color:transparent!important;user-select:none!important;position:relative!important;pointer-events:none!important}
#bottombar .bb-icon,#bottombar .bb-label{pointer-events:none!important}.bb-icon{font-size:21px!important;line-height:24px!important}.bb-label{font-size:10px!important;line-height:14px!important;white-space:nowrap!important}.bb-item.active{background:var(--red-bg,#2a0000)!important;color:#fff!important}
#bplus-touch-proxy{position:fixed!important;left:0!important;right:0!important;bottom:0!important;width:100%!important;height:calc(76px + env(safe-area-inset-bottom))!important;padding:6px 6px env(safe-area-inset-bottom)!important;display:flex!important;z-index:2147483647!important;pointer-events:none!important;touch-action:none!important}
#bplus-touch-proxy .bplus-touch-slot{flex:1!important;min-width:0!important;height:56px!important;border-radius:10px!important;pointer-events:auto!important;touch-action:manipulation!important;-webkit-tap-highlight-color:transparent!important;background:transparent!important}
#mob-overlay{display:none!important;pointer-events:none!important;z-index:1!important}.sidebar{z-index:2147483001!important}.modal-overlay{z-index:2147483002!important}.notif-panel{z-index:2147483003!important}
button,a,input,select,textarea,[role=button]{touch-action:manipulation;-webkit-tap-highlight-color:transparent}button{min-height:42px}.btn-icon{min-width:42px}
@media(max-width:700px){body{font-size:14px!important}.topbar{height:56px!important;padding:0 10px!important}.content{padding:12px 10px calc(100px + env(safe-area-inset-bottom))!important}.page-title{font-size:16px!important}.grid,.two-col,.three-col{grid-template-columns:1fr!important}.modal{width:calc(100vw - 20px)!important;max-width:none!important;max-height:calc(100dvh - 24px)!important}.modal-body{overflow-y:auto!important;-webkit-overflow-scrolling:touch!important}.form-row{grid-template-columns:1fr!important}.table-wrap{max-width:100%!important;overflow-x:auto!important}.table{min-width:620px}.sidebar{width:min(86vw,320px)!important}.notif-panel{width:min(92vw,360px)!important;max-height:calc(100dvh - 56px)!important}}
@media(max-width:420px){#bottombar .bb-icon{font-size:19px!important}.bb-label{font-size:9px!important}.content{padding-left:8px!important;padding-right:8px!important}.topbar-left img{display:none!important}}
`;
const MOBILE_JS=`<script id="bplus-mobile-script">(()=>{
const isMobile=()=>matchMedia('(max-width:700px)').matches;
const getItems=()=>{const b=document.getElementById('bottombar');if(!b)return[];let a=[...b.querySelectorAll('.bb-item')];if(!a.length)a=[...b.querySelectorAll('button,a,[role="button"]')];return a};
const visible=el=>{if(!el)return false;const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};
const modalOpen=()=>[...document.querySelectorAll('.modal-overlay,.modal,.notif-panel')].some(visible);
const invoke=el=>{if(!el)return;el.scrollIntoView?.({block:'nearest',inline:'nearest'});const ev=new MouseEvent('click',{view:window,bubbles:true,cancelable:true});el.dispatchEvent(ev);};
const build=()=>{if(!isMobile())return;const items=getItems();if(!items.length)return;let p=document.getElementById('bplus-touch-proxy');if(!p){p=document.createElement('div');p.id='bplus-touch-proxy';document.body.appendChild(p)}p.innerHTML='';items.forEach((item,i)=>{const slot=document.createElement('div');slot.className='bplus-touch-slot';slot.setAttribute('aria-label',item.getAttribute('aria-label')||item.innerText?.trim()||('nav-'+i));let down=false;slot.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;down=true;e.preventDefault();e.stopPropagation()},{passive:false});slot.addEventListener('pointerup',e=>{if(e.pointerType==='mouse')return;e.preventDefault();e.stopPropagation();if(down&&!modalOpen())invoke(item);down=false},{passive:false});slot.addEventListener('touchstart',e=>{e.preventDefault();e.stopPropagation()},{passive:false});slot.addEventListener('touchend',e=>{e.preventDefault();e.stopPropagation();if(!modalOpen())invoke(item)},{passive:false});slot.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(!modalOpen())invoke(item)});p.appendChild(slot)});p.style.display=modalOpen()?'none':'flex'};
const refresh=()=>{const p=document.getElementById('bplus-touch-proxy');if(p)p.style.display=isMobile()&&!modalOpen()?'flex':'none'};
const start=()=>{build();refresh();setTimeout(build,100);setTimeout(build,400);setTimeout(build,1000);const mo=new MutationObserver(()=>{build();refresh()});mo.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class','style']});window.addEventListener('resize',()=>{build();refresh()});};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();</script>`;
self.addEventListener('install',e=>self.skipWaiting());
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const url=new URL(e.request.url);e.respondWith(fetch(e.request,{cache:'no-store'}).then(async r=>{if(!r.ok)return r;if(url.pathname.endsWith('/app.html')){let h=await r.text();h=h.replace('<div class="app"<div class="app" id="app-main" style="display:none">','<div class="app" id="app-main" style="display:flex">');if(!h.includes('bplus-mobile-patch'))h=h.replace('</head>','<style id="bplus-mobile-patch">'+MOBILE_CSS+'</style></head>');if(!h.includes('bplus-mobile-script'))h=h.replace('</body>',MOBILE_JS+'</body>');return new Response(h,{status:r.status,statusText:r.statusText,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}})}return r}).catch(()=>caches.match(e.request)))});
self.addEventListener('push',e=>{const d=e.data?e.data.json():{};e.waitUntil(self.registration.showNotification(d.title||'B+ Gestionale',{body:d.body||'',icon:'./icons/icon-192.png',badge:'./icons/icon-72.png',tag:d.tag||'bplus',data:{url:d.url||'./'}}))});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil(clients.openWindow(e.notification.data?.url||'./'))});
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING'){self.skipWaiting();e.source?.postMessage({type:'SW_UPDATED'})}});